# HEADER:

# NAME: M.KARTHIK
# ROLL NO: CS20B048
# COURSE: CS3205 JAN 2023 SEMISTER
# LAB NUMBER : 4
# DATE OF SUBMISSION : 05-04-2023
# I confirm that the source file is entirely written by me without resorting to any dishonest means
# WEIBISTES that is used : i didn't used any wibesites i have done all by my own

run1:
	python3 server.py -d -p 20001 -n 50 -e 0.1

run2:
	python3 client.py -d -l 512 -r 10 -f 10 -w 5 -n 50 -s 127.0.0.1 -p 20001


