run1:
	python3 ospf.py -i 1 -f "input_file1.txt" -h 1 -a 5 -s 20

run2:
	python3 ospf.py -i 2 -f "input_file2.txt" -h 1 -a 5 -s 20


# HEADER:

# NAME: M.KARTHIK
# ROLL NO: CS20B048
# COURSE: CS3205 JAN 2023 SEMISTER
# LAB NUMBER : 5
# DATE OF SUBMISSION : 28-04-2023
# I confirm that the source file is entirely written by me without resorting to any dishonest means
# WEIBISTES that is used : i didn't used any wibesites i have done all by my own

