#NAME               : M.KARHIK
#Roll Number        : CS20B048
#Course             : CS3205 Jan. 2023 semister
#Lab number         : 2
#Date of submission : 04-03-2023
#I confirm that the source file is entirely written by me
#without resorting to any dishonest means.
#website(s) : i didn't took the help of any website i have written on my own

run:
	python3 Q1.py

clean:
	rm -rf ADS.output NR.output RDS.output TDS.output



